services:
  - type: web
    name: cheezy-mood-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CASHIER_FRONTEND_URL
        sync: false
      - key: CASHIER_API_KEY
        sync: false
      - key: RESTAURANT_TIMEZONE
        value: Africa/Tunis
      - key: OPENING_TIME
        value: "12:00"
      - key: CLOSING_TIME
        value: "21:00"
      - key: CLOSING_SOON_MINUTES
        value: "60"
